import {test,expect} from '@playwright/test';
import {mobileSignIn} from './mobile-session';
import {writeFile} from 'node:fs/promises';

test('shared phone capture reaches backend review and branch leader confirmation',async({page,browser,request})=>{
 test.setTimeout(240000);
 let created:any;
 page.on('response',async r=>{if(r.request().method()==='POST' && new URL(r.url()).pathname==='/api/kyc-captures' && r.ok()) created=await r.json();});
 await mobileSignIn(page);
 await page.getByRole('tab',{name:'Capture',exact:true}).click();
 await page.getByRole('button',{name:'Upload photo',exact:true}).click();
 await expect(page.getByRole('button',{name:'Document captured View',exact:true})).toBeVisible({timeout:60000});
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Scan order',exact:true}).click();
 await expect(page.getByRole('button',{name:'Document captured View',exact:true})).toBeVisible({timeout:60000});
 await page.screenshot({path:'../output/qa/shared-order-details.png'});
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await expect(page.getByRole('button',{name:'Upload',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Upload',exact:true}).click();
 await page.getByRole('button',{name:'Upload payment confirmation',exact:true}).click();
 await expect(page.getByRole('group',{name:/Payment recorded.*Pending backend confirmation/}).first()).toBeVisible({timeout:60000});
 await expect.poll(()=>!!created).toBeTruthy();
 await page.waitForTimeout(2200);
 await page.screenshot({path:'../output/qa/shared-payment-invoice.png'});
 await writeFile('../output/qa/shared-capture-id.txt',created.id);
 const signIn=async(email:string)=>{
  const r=await request.post('/api/auth/login',{data:{email,password:process.env.DEMO_PASSWORD,native:true}});expect(r.ok()).toBeTruthy();return r.json();
 };
 const agent=await signIn('agent1@relay.demo');const headers={Authorization:`Bearer ${agent.access_token}`};
 const url=`/api/kyc-captures/${created.id}`;let capture:any;
 await expect.poll(async()=>{capture=await(await request.get(url,{headers})).json();return capture.status;},{timeout:60000}).toBe('EXTRACTED');
 const validated=await request.patch(url+'/rows',{headers,data:{version:capture.version,rows:capture.rows,reason:'Checked order confirmation screenshot'}});expect(validated.ok(),await validated.text()).toBeTruthy();capture=await validated.json();
 const submit=await request.post(url+'/submit',{headers,data:{version:capture.version}});expect(submit.ok()).toBeTruthy();
 const adminContext=await browser.newContext();const admin=await adminContext.newPage();
 await admin.goto('/');await admin.locator('input[type=email]').fill('admin@relay.demo');await admin.locator('input[type=password]').fill(process.env.DEMO_PASSWORD!);await admin.getByRole('button',{name:'Sign in to workspace'}).click();
 await expect(admin.locator('input[type=password]')).toBeHidden();await admin.goto('/kyc-capture');
 await admin.getByRole('button',{name:new RegExp(created.source_reference)}).first().click();
 await expect(admin.getByRole('heading',{name:'Payment details',exact:true})).toBeVisible();
 await admin.getByRole('button',{name:'Order details',exact:true}).click();
 await expect(admin.locator('img[alt*="Order"]')).toBeVisible();
 await admin.screenshot({path:'../output/qa/shared-backend-order-comparison.png'});
 await admin.getByRole('button',{name:'Payment confirmation',exact:true}).first().click();
 await admin.getByRole('checkbox',{name:/I checked/}).check();await admin.getByRole('textbox',{name:'Review note'}).fill('Customer, order and agent payment record compared with uploaded screens.');
 await admin.getByRole('button',{name:'Verify submission',exact:true}).click();
 await expect(admin.getByText(/Awaiting branch team leader confirmation/)).toBeVisible();
 const leaderContext=await browser.newContext();const leader=await leaderContext.newPage();await mobileSignIn(leader,'leader2@relay.demo');
 await expect(leader.getByRole('group',{name:/Backend verified.*SAMPLE-REQ-1001/}).first()).toBeVisible({timeout:30000});
 await leader.screenshot({path:'../output/qa/shared-leader-confirmation.png'});
 await leader.getByRole('button',{name:'Confirm',exact:true}).first().click();
 await expect.poll(async()=>{const r=await request.get(url,{headers});return(await r.json()).leader_confirmation?.name;},{timeout:20000}).toBeTruthy();
 await admin.waitForTimeout(6000);await admin.screenshot({path:'../output/qa/shared-backend-confirmed.png'});
 await leaderContext.close();await adminContext.close();
});
